### ISSUE TITLE
Checksum issue in mongo-driver v1.4.5

### ISSUE THREAD

**Issue by ilyakaznacheev** [romnn/testcontainers#8] opened 2021-12-24 11:58 UTC
We ran into a problem when using the library because of a mongo-driver dependency with an invalid checksum.

The checksum problem is described here: https://jira.mongodb.org/projects/GODRIVER/issues/GODRIVER-1851?filter=allissues

To fix that they suggest bumping the version to 1.4.6.

**Comment by romnn** [comment] 2022-10-20 21:49
closing as duplicate of PR #7

**Closed by romnn** 2022-10-20 21:49 UTC
